import { StyleSheet, Text, View, Image } from "react-native";
import React, { useLayoutEffect } from "react";
import { SafeAreaView } from "react-native-safe-area-context";
import Colors from "../constants/colors";
import { useNavigation } from "@react-navigation/native";
import TicketInput from "./TicketInput";
import SwitchSection from "./SwitchSection";
import PrimaryButton from "./PrimaryButton";
import { Ionicons } from "@expo/vector-icons";

function AddEventTicket({ route }) {
  const navigation = useNavigation();

  useLayoutEffect(() => {
    navigation.setOptions({
      headerTitle: () => {
        return (
          <Image
            style={[{ width: 75, height: 24 }]}
            source={require("../assets/images/wegoBlackLogo.png")}
          />
        );
      },

      headerStyle: {
        borderBottomWidth: 0,
      },
      headerTransparent: true,
    });
  }, [navigation]);

  function pressHandler(){
    navigation.navigate('AddEventTicketFinal', {})
  }
  return (
    <View style={styles.ticketOuter}>
      <View style={styles.upperOuter}>
        <View style={styles.imageOuter}>
            <Ionicons name="image-outline" size={24} color={Colors.black[100]}/>
            <Text style={{
              fontFamily: "Poppins_400Regular",
              color: Colors.black[300],
              fontSize: 12,
              width: '50%',
              textAlign:'center'
            }}>Event image will be generated by AI.</Text>
        </View>
        <Text style={styles.textTitle}>{route.params.title}</Text>

        <View style={styles.locationInformationOuter}>
          <Text
            style={{
              fontFamily: "Poppins_400Regular",
              color: Colors.black[400],
            }}
            children={"Location"}
          />
          <Text
            style={{
              fontFamily: "Poppins_500Medium",
              color: Colors.black.default,
            }}
            children={"Location Information"}
          />

          <View style={{
            flexDirection: 'row',
            justifyContent: 'space-between'
          }}>
            <TicketInput children={"Date"} inputPlaceholder={'dd.mm.yyyy'} />
            <TicketInput children={"Time"} inputPlaceholder={'00:00'}/>
            <TicketInput children={"Capacity"} inputPlaceholder={'00'}/>

          </View>
          <TicketInput children={"Description"} heightBox={100} inputPlaceholder={'Mention about your event...'}/>
          <SwitchSection title={'Participant Restriction'} infoFalse={"Private Event"} infoTrue={"Public Event"}/>
        </View>
      </View>
    
      
       <View style={{
        width: '100%',
        height: '8%',
        justifyContent: 'center',
        alignItems: 'center'
       }}>
       <Image
        style={{ width: "100%",
         }}
        resizeMode="contain"
        source={require("../assets/images/TicketCircles.png")}
      /> 
</View>
<PrimaryButton 
        children={"Publish Event"} 
        buttonColor={Colors.blue.default}
        buttonFontFamily={'Poppins_700Bold'}
        verticalMargin={0}
        onPress={pressHandler}/>
     
    </View>
  );
}

export default AddEventTicket;

const styles = StyleSheet.create({
  locationInformationOuter: {},
  textTitle: {
    fontFamily: "Poppins_700Bold",
    fontSize: 18,
    paddingVertical: 14,
  },
  upperOuter: {
    paddingHorizontal: 16,
    flex: 1,
  },
  ticketOuter: {
    marginHorizontal: 16,
    marginTop: "25%",
    marginBottom: "10%",
    borderWidth: 1,
    borderColor: Colors.white[300],
    borderRadius: 40,
    flex: 1,
    paddingVertical: 16,
    justifyContent: 'space-between'
  },
  imageOuter: {
    width: "100%",
    height: "30%",
    backgroundColor: Colors.white[100],
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center'
  },
});
